#cloud-config

hostname: rancher
rancher:
  console: ubuntu
  network:
    interfaces:
      eth0:
        bridge: true
        dhcp: false
        address: 10.0.10.3/24
        gateway: 10.0.10.1
        mtu: 1500
    dns:
      nameservers:
      - 10.0.10.1
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      apt-get -y update
      apt-get -y install python